[package]
name = "css2tw-core"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
anyhow.workspace = true
rayon.workspace = true
ignore.workspace = true
lightningcss = "1.0.0-alpha.71"
cssparser = "0.33.0"
oxc_allocator = "0.129.0"
oxc_ast = "0.129.0"
oxc_parser = "0.129.0"
oxc_span = "0.129.0"
similar = "3.1.0"
oxc_traverse = "0.129.0"
oxc_ast_visit = "0.129.0"
regex = "1.12.3"
scraper = "0.22.0"
selectors = "0.26.0"
